languageCode = "en"
languageName = "English"
weight = 1
title = "Xuan T."

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Xuan T."
  email = "xuantan.co@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "portfolio of works"
  bio = "making things."
  links = [
    { instagram = "https://instagram.com/xuantt" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]