languageCode = "en"
languageName = "English"
weight = 1
title = "Xuan T."

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/profile.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Xuan T."
  email = "xuantan.co@gmail.com"
  image = "images/profile.png"
  headline = "Making Things"
  bio = "making things."
  links = [
    { instagram = "https://instagram.com/xuantt" },
    { linkedin = "https://linkedin.com/in/xuantt" },
  ]